### ISSUE TITLE
About pure rotation

### ISSUE THREAD

**Issue by ljjTYJR** [princeton-vl/MultiSlam_DiffPose#1]
Hi,
Thanks for the nice work.

In my experiments, I found the method and also $\texttt{DPVO}$ is robust to rotation-only motions.

To my understanding, the optimization of depth based on the optical flow should be similar to feature tracking-based methods (like ORB-SLAM), but ORB-SLAM can get lost easily in such cases.

Do you know some reasons?

Best.

**Comment by lahavlipson** [comment]
One possibility is that the bundle adjustment stages of DPVO and the proposed multi-session SLAM both use an inverse depth parameterization, which is more stable when dealing with points at infinity. In contrast, ORB-SLAM points as free variables in 3D space, if I am not mistaken.
